version: '3.7'

services:
  database_rentacars:
    image: mysql
    container_name: database_rentacars_mysql
    restart: always
    ports:
      - 3306:3306
    
    environment:
      - MYSQL_ROOT=docker_mysql
      - MYSQL_ROOT_PASSWORD=docker_mysql
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=rentacars
      - MYSQL_DB=rentacars
    volumes:
      - psdata:/data/mysql
    #network_mode: host
    
  app:
    build: .
    container_name: rentacars
    #restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    #network_mode: host

volumes:
  psdata: