version: '3.7'

services:
  database_rentacars:
    image: postgres
    container_name: database_rentacars
    restart: always
    ports:
      - 5432:5432
    
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentacars
      - POSTGRES_DB=rentacars
    volumes:
      - psdata:/data/postgres
    #network_mode: host
    
  app:
    build: .
    container_name: rentacars
    #restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    #network_mode: host

volumes:
  psdata: